# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "早安，歡迎｜陳泰亨"

# This page should be the root of your website. It's important.
page = "https://accessible-dog-ab2.notion.site/96d2649f553347b7b784cfbc5cfe4d07?pvs=4"
